"""
Django settings for KwiqHome project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ys%$l&1bfe$@f=ium)3f0_u%#&%5@f6)x+4u6=y*h$b0tz-ry('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'sorl.thumbnail',
    'auditlog', 
    'django_filters',
    'import_export',
    'rangefilter',
    'Schedules',
    'Portal',
    'Projects',
    'Leads',
    'baton.autodiscover'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'django_auto_logout.middleware.auto_logout',
]


AUTO_LOGOUT = {
    'IDLE_TIME': 60,
    'SESSION_TIME': 120,
    'MESSAGE': 'The session has expired. Please login again to continue.',
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}

APPEND_SLASH  = True

ROOT_URLCONF = 'KwiqHome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FileUploadParser',
    ],
}

WSGI_APPLICATION = 'KwiqHome.wsgi.application'

GOOGLE_MAPS_API_KEY = 'your-key-goes-here'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'safetybrain',
        'USER': 'postgres',
        'PASSWORD': 'safetybrain',
        'HOST': 'localhost',
        'PORT': '',
    }
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'safetybrain',
        'USER': 'root',
        'PASSWORD': 'Password',
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}
'''

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE =  'Asia/Dubai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
   os.path.join(BASE_DIR, 'static'),
]

#STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = 'media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


THUMBNAILS = {
    'METADATA': {
        'BACKEND': 'thumbnails.backends.metadata.DatabaseBackend',
    },
    'STORAGE': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        # You can also use Amazon S3 or any other Django storage backends
    },
    'SIZES': {
        'small': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 10, 'height': 10},
                {'PATH': 'thumbnails.processors.crop', 'width': 80, 'height': 80}
            ],
            'POST_PROCESSORS': [
                {
                    'PATH': 'thumbnails.post_processors.optimize',
                    'png_command': 'optipng -force -o7 "%(filename)s"',
                    'jpg_command': 'jpegoptim -f --strip-all "%(filename)s"',
                },
            ],
        },
        'large': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 20, 'height': 20},
                {'PATH': 'thumbnails.processors.flip', 'direction': 'horizontal'}
            ],
        },
        'watermarked': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 20, 'height': 20},
                # Only supports PNG. File must be of the same size with thumbnail (20 x 20 in this case)
                {'PATH': 'thumbnails.processors.add_watermark', 'watermark_path': 'watermark.png'}
            ],
        }
    }
}

BATON = {
    'SITE_HEADER': 'Take A Home',
    'SITE_TITLE': 'Take A Home',
    'INDEX_TITLE': 'Site administration',
    'SUPPORT_HREF': 'https://www.takeahome.in/',
    'COPYRIGHT': 'copyright © 2023 <a href="https://www.takeahome.in/">Presight</a>', # noqa
    'POWERED_BY': '<a href="https://www.takeahome.in/">Presight AI</a>',
    'CONFIRM_UNSAVED_CHANGES': True,
    'SHOW_MULTIPART_UPLOADING': True,
    'ENABLE_IMAGES_PREVIEW': True,
    'COLLAPSABLE_USER_AREA': True,
    'CHANGELIST_FILTERS_IN_MODAL': True,
    'CHANGELIST_FILTERS_ALWAYS_OPEN': True,
    'CHANGELIST_FILTERS_FORM': True,
    'MENU_ALWAYS_COLLAPSED': False,
    'MENU_TITLE': 'Menu',
    'MESSAGES_TOASTS': True,
    'GRAVATAR_DEFAULT_IMG': '',
    'GRAVATAR_ENABLED': True,
    'LOGIN_SPLASH': '/static/gradient.png',
    'MENU': (
        { 'type': 'title', 'label': 'main', 'apps': ('auth',) },
        {
            'type': 'app',
            'name': 'auth',
            'label': 'Authentication',
            'icon': 'fa fa-lock',
            'models': (
                {
                    
                    'icon': 'fa fa-user',
                    'name': 'user',
                    'label': 'Users'
                },
                {
                    
                    'icon': 'fa fa-users',
                    'name': 'group',
                    'label': 'Groups'
                },
            )
        },
        { 'type': 'title', 'label': 'main', 'apps': ('projects',) },
        {
            'type': 'app',
            'name': 'projects',
            'label': 'Projects',
            'icon': 'fa fa-lock',
            'models': (
                {
                    
                    'icon': 'fa fa-user',
                    'name': 'developer',
                    'label': 'Developer'
                },
            )
        },
        { 'type': 'title', 'label': 'Portal', 'apps': ('portal','auditlog' ) },
        {
            'type': 'app',
            'name': 'portal',
            'label': 'Portal',
            'icon': 'fa fa-lock',
            'models': (
                {
                    'icon': 'fa fa-mobile-alt',
                    'name': 'device',
                    'label': 'Devices'
                },
                {
                    'icon': 'fa fa-box',
                    'name': 'parameter',
                    'label': 'Parameters'
                },
                {
                    'icon': 'fa fa-database',
                    'name': 'incident',
                    'label': 'Incidents'
                },
                {
                    'icon': 'fa fa-heart',
                    'name': 'healthdetail',
                    'label': 'Health Details'
                },
                {
                    'icon': 'fa fa-shield',
                    'name': 'safetydetail',
                    'label': 'Safety Details'
                },
                {
                    'icon': 'fa fa-artstation',
                    'name': 'item',
                    'label': 'Items'
                },
                {
                    'icon': 'fa fa-person',
                    'name': 'person',
                    'label': 'Persons'
                },
                {
                    
                    'icon': 'fa fa-user',
                    'name': 'profile',
                    'label': 'Profiles'
                },
                
            )
        },
        {
            'type': 'app',
            'name': 'auditlog',
            'label': 'Audit Log',
            'icon': 'fa fa-lock',
            'models': (
                {
                    'icon': 'fa fa-clipboard-check',
                    'name': 'logentry',
                    'label': 'Log Entries'
                },
            )
        },
        # { 'type': 'title', 'label': 'Contents', 'apps': ('portal', ) },
        # { 'type': 'model', 'label': 'Pages', 'name': 'device', 'app': 'portal' },
        # { 'type': 'free', 'label': 'Custom Link', 'url': 'http://www.google.it', 'perms': ('flatpages.add_flatpage', 'auth.change_user') },
        # { 'type': 'free', 'label': 'My parent voice', 'children': [
        #     { 'type': 'model', 'label': 'A Model', 'name': 'profile', 'app': 'portal' },
        #     { 'type': 'free', 'label': 'Another custom link', 'url': 'http://www.google.it' },
        # ] },
    )
}